import { Gig, Order, User } from '@/types'

export const mockSellers: User[] = [
  {
    id: 'seller-1',
    name: 'Arjun Mehta',
    email: 'arjun@example.com',
    role: 'SELLER',
    isSeller: true,
    sellerBio: 'Final year CS student at IIT Bombay. Specializing in AI/ML and Python backends.',
    skills: 'Python, LangChain, FastAPI, PyTorch',
    createdAt: '2024-01-15',
  },
  {
    id: 'seller-2',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    role: 'SELLER',
    isSeller: true,
    sellerBio: 'MERN stack developer and competitive programmer. NIT Trichy.',
    skills: 'React, Node.js, MongoDB, Next.js',
    createdAt: '2024-02-10',
  },
  {
    id: 'seller-3',
    name: 'Rahul Nair',
    email: 'rahul@example.com',
    role: 'SELLER',
    isSeller: true,
    sellerBio: 'Data science enthusiast with publication experience. VIT Chennai.',
    skills: 'Python, Pandas, NumPy, Scikit-learn, SQL',
    createdAt: '2024-03-01',
  },
]

export const mockGigs: Gig[] = [
  {
    id: 'gig-1',
    title: 'Build a Production-Ready LangChain RAG System with FastAPI Backend',
    description: 'I will build a complete Retrieval-Augmented Generation (RAG) pipeline for your documents, PDFs, or knowledge base using LangChain, FAISS vector store, and a FastAPI backend. Includes streaming responses and source attribution.',
    category: 'AI Automation',
    techStack: 'LangChain, FastAPI, FAISS, OpenAI, Python',
    status: 'PUBLISHED',
    basicPrice: 4999,
    basicDesc: 'Basic RAG pipeline, up to 100 docs, API endpoint',
    standardPrice: 9999,
    standardDesc: 'Full pipeline + streaming + auth + deployment guide',
    premiumPrice: 18999,
    premiumDesc: 'Enterprise-grade RAG, multi-modal, custom embeddings, 1hr call',
    deliveryDays: 7,
    totalOrders: 34,
    rating: 4.9,
    sellerId: 'seller-1',
    seller: mockSellers[0],
    createdAt: '2024-06-01',
  },
  {
    id: 'gig-2',
    title: 'Full-Stack Django + React SaaS Application with Stripe & Auth',
    description: 'I will build a complete SaaS web application using Django REST Framework on the backend and React/Next.js on the frontend. Includes JWT authentication, subscription billing, and admin panel.',
    category: 'Web Development',
    techStack: 'Django, React, PostgreSQL, Stripe, JWT',
    status: 'PUBLISHED',
    basicPrice: 7999,
    basicDesc: 'Core app with auth and basic CRUD operations',
    standardPrice: 14999,
    standardDesc: 'Full SaaS with billing, roles, and admin panel',
    premiumPrice: 24999,
    premiumDesc: 'Enterprise setup + CI/CD + Docker + 30 days support',
    deliveryDays: 14,
    totalOrders: 21,
    rating: 4.8,
    sellerId: 'seller-2',
    seller: mockSellers[1],
    createdAt: '2024-06-10',
  },
  {
    id: 'gig-3',
    title: 'Complete Data Analysis Report with Visualizations and ML Predictions',
    description: 'Professional data analysis using Python. I will clean your dataset, perform exploratory analysis, build predictive ML models, and deliver a comprehensive report with interactive visualizations.',
    category: 'Data Science',
    techStack: 'Python, Pandas, Scikit-learn, Plotly, Jupyter',
    status: 'PUBLISHED',
    basicPrice: 2999,
    basicDesc: 'EDA + 5 visualizations + summary report',
    standardPrice: 5999,
    standardDesc: 'Full analysis + ML model + prediction endpoint',
    premiumPrice: 10999,
    premiumDesc: 'Complete data product: pipeline + dashboard + model API',
    deliveryDays: 5,
    totalOrders: 47,
    rating: 4.7,
    sellerId: 'seller-3',
    seller: mockSellers[2],
    createdAt: '2024-05-20',
  },
  {
    id: 'gig-4',
    title: 'Customer Support Automation Agent Using OpenAI Function Calling',
    description: 'Build an intelligent customer support chatbot that understands your product docs, answers FAQs, escalates complex queries, and integrates with your CRM via OpenAI function calling.',
    category: 'AI Automation',
    techStack: 'OpenAI, Python, FastAPI, Redis, Pinecone',
    status: 'PUBLISHED',
    basicPrice: 5999,
    basicDesc: 'Basic chatbot with FAQ support and webhook',
    standardPrice: 11999,
    standardDesc: 'Full agent with CRM integration and escalation logic',
    premiumPrice: 21999,
    premiumDesc: 'Multi-channel agent (web + WhatsApp) + analytics dashboard',
    deliveryDays: 10,
    totalOrders: 18,
    rating: 4.6,
    sellerId: 'seller-1',
    seller: mockSellers[0],
    createdAt: '2024-06-15',
  },
  {
    id: 'gig-5',
    title: 'Next.js 14 App Router E-Commerce Store with CMS and Payment Gateway',
    description: 'Complete e-commerce solution built with Next.js 14 App Router, Tailwind CSS, and your choice of payment gateway. Includes product management CMS, cart, wishlist, and order tracking.',
    category: 'Web Development',
    techStack: 'Next.js, Tailwind, Prisma, Razorpay, Contentful',
    status: 'PUBLISHED',
    basicPrice: 9999,
    basicDesc: 'Storefront with product listing and cart',
    standardPrice: 17999,
    standardDesc: 'Full store with CMS, payments, and order management',
    premiumPrice: 28999,
    premiumDesc: 'Enterprise store + multi-vendor + analytics + SEO',
    deliveryDays: 21,
    totalOrders: 12,
    rating: 4.9,
    sellerId: 'seller-2',
    seller: mockSellers[1],
    createdAt: '2024-07-01',
  },
  {
    id: 'gig-6',
    title: 'DSA Problem Solving & Algorithm Implementation in Java or Python',
    description: 'Expert implementation of data structures and algorithms for academic projects, competitive programming, or technical interviews. Clean code with comments, time-complexity analysis included.',
    category: 'CS Academic',
    techStack: 'Java, Python, C++, Algorithms, DS',
    status: 'PUBLISHED',
    basicPrice: 999,
    basicDesc: '5 problems with explanations and complexity analysis',
    standardPrice: 2499,
    standardDesc: '15 problems + full report + code walkthrough',
    premiumPrice: 4999,
    premiumDesc: 'Complete topic coverage + viva prep session',
    deliveryDays: 3,
    totalOrders: 89,
    rating: 4.8,
    sellerId: 'seller-3',
    seller: mockSellers[2],
    createdAt: '2024-04-10',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    package: 'Standard',
    price: 9999,
    status: 'IN_PROGRESS',
    requirements: 'I need a RAG system for our 200-page product manual. Users should be able to ask questions and get accurate answers with source references.',
    deadline: '2025-04-20',
    gigId: 'gig-1',
    gig: mockGigs[0],
    buyerId: 'buyer-1',
    buyer: { id: 'buyer-1', name: 'Vikram Industries', email: 'vikram@example.com', role: 'BUYER', isSeller: false, createdAt: '2024-11-01' },
    sellerId: 'seller-1',
    seller: mockSellers[0],
    createdAt: '2025-04-10',
  },
  {
    id: 'order-2',
    package: 'Basic',
    price: 2999,
    status: 'DELIVERED',
    requirements: 'Sales data for Q1 2025. Need churn prediction and revenue forecast.',
    deadline: '2025-04-15',
    gigId: 'gig-3',
    gig: mockGigs[2],
    buyerId: 'buyer-1',
    buyer: { id: 'buyer-1', name: 'Vikram Industries', email: 'vikram@example.com', role: 'BUYER', isSeller: false, createdAt: '2024-11-01' },
    sellerId: 'seller-3',
    seller: mockSellers[2],
    createdAt: '2025-04-05',
  },
]
